config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :applicants, only: %i[index show create new] do
    resources :credit_solicitations, only: %i[create new index]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :applicant

  validates :applicant, presence: true
  validates :street, presence: true
  validates :number, presence: true
  validates :zip_code, presence: true
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  has_many :phones, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :credit_solicitations, dependent: :destroy

  accepts_nested_attributes_for :phones
  accepts_nested_attributes_for :addresses

  validates :phones, length: { minimum: 1 }
  validates :addresses, length: { minimum: 1 }
  validates :user, presence: true
  validates :social_name, presence: true
  validates :cnpj, presence: true, uniqueness: true

  scope :for_user, ->(user) { joins(:user).where('user_id = ?', user.id) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit_solicitation.rb
class CreditSolicitation < ApplicationRecord
  belongs_to :applicant
  belongs_to :plot_tax
  has_many :plots, dependent: :destroy

  validates :value, presence: true
  validates :plot_tax_id, presence: true
  validate :dont_have_open_plot

  before_create :add_interest_rate
  before_create :calculate_plots_value
  before_create :calculate_value_with_rate
  before_create :make_plots

  def self.with_open_plots(applicant_id)
    credit_solicitation = where(applicant_id: applicant_id).last
    credit_solicitation.plots = Plot.open(credit_solicitation.id)
    credit_solicitation
  end

  private

  def dont_have_open_plot
    credit_solicitation = CreditSolicitation.where(applicant_id: applicant_id)
                                            .last
    return if credit_solicitation.blank?

    plots = Plot.open(credit_solicitation.id)
    return errors.add(:applicant, 'Já tem empréstimos abertos') if plots.any?
  end

  def add_interest_rate
    self.interest_rate = plot_tax.tax
    self.plots_amount = plot_tax.plot
  end

  def calculate_plots_value
    self.plots_value = calculate_pmt
  end

  def calculate_value_with_rate
    self.value_with_rate = plots_value * plots_amount
  end

  def calculate_pmt
    pv = (1 + interest_rate)**plots_amount
    (pv * interest_rate / (pv - 1)) * value
  end

  def make_plots
    date = 1.month.from_now
    end_date = plots_amount.months.from_now
    while date < end_date
      plots << Plot.new(payment_day: date, value: plots_value)
      date += 1.month
    end
  end
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :applicant

  validates :applicant, presence: true
  validates :number, presence: true, uniqueness: true
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :credit_solicitation

  validates :payment_day, presence: true
  validates :value, presence: true

  def self.open(credit_solicitation)
    where('credit_solicitation_id = :credit_solicitation AND
      payment_day > :today', credit_solicitation: credit_solicitation,
                             today: Date.current)
  end
end

app/models/plot_tax.rb
class PlotTax < ApplicationRecord
  validates :plot, presence: true
  validates :tax, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :applicants, dependent: :destroy
  has_many :phones, through: :applicants
  has_many :addresses, through: :applicants
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @applicants = Applicant.where(user: current_user)
  end

  def show
    @applicant = Applicant.for_user(current_user).find(params[:id])
  end

  def new
    @applicant = Applicant.new
    @applicant.addresses.build
    @applicant.phones.build
  end

  def create
    @applicant = Applicant.new(applicant_params)
    @applicant.user = current_user
    if @applicant.save
      return redirect_to @applicant, notice: 'Empresa cadastrada'
    end

    render :new
  end

  private

  def applicant_params
    params.require(:applicant)
          .permit(:social_name, :cnpj, phones_attributes: %i[number],
                                       addresses_attributes: %i[street number
                                                                complement
                                                                zip_code])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def record_not_found
    flash[:notice] = 'Recurso não encontrado'
    redirect_to root_path
  end
end

app/controllers/credit_solicitations_controller.rb
class CreditSolicitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :validates_user_applicant

  def index
    @credit_solicitation = CreditSolicitation
                           .with_open_plots(params[:applicant_id])
  end

  def new
    @plot_taxes = PlotTax.all
    @credit_solicitation = CreditSolicitation
                           .new(applicant_id: params[:applicant_id])
  end

  def create
    @credit_solicitation = CreditSolicitation.new(credit_solicitation_params)
    if @credit_solicitation.save
      return redirect_to(applicant_credit_solicitations_path(
                           @credit_solicitation.applicant
                         ),
                         notice: 'Solicitação criada')
    end
    @plot_taxes = PlotTax.all
    render :new
  end

  private

  def validates_user_applicant
    @applicant = Applicant.where(user: current_user, id: params[:applicant_id])
    redirect_to root_path if @applicant.empty?
  end

  def credit_solicitation_params
    params.require(:credit_solicitation)
          .permit(:value, :plot_tax_id, :applicant_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/_address_fields.html.erb
<div class='nested-fields'>

  <div class='addressFields'>
    <div class='field'>
      <%= f.label :street, class: 'address-street-label'%>
      <%= f.text_field :street %>
    </div>

    <div class='field'>
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div class='field'>
      <%= f.label :complement %>
      <%= f.text_field :complement %>
    </div>

    <div class='field'>
      <%= f.label :zip_code %>
      <%= f.text_field :zip_code %>
    </div>
  </div>
  <%= link_to_remove_association t('addresses.remove'), f %>
</div>

app/views/applicants/_form.html.erb
<%= form_with model: @applicant, local: true do |f| %>
  <div class='field'>
    <%= f.label :social_name %>
    <%= f.text_field :social_name %>
  </div>

  <div class='field'>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>

  <div id='phones'>
    <%= f.fields_for :phones do |p| %>
      <%= render 'phone_fields', f: p %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association t('phones.add'), f, :phones %>
    </div>
  </div>

  <div id='addresses'>
    <%= f.fields_for :addresses do |a| %>
      <%= render 'address_fields', f: a %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association t('addresses.add'), f, :addresses %>
    </div>
  </div>

  <div class='submit'>
    <%= f.submit 'Registrar' %>
  </div>

<% end %>

app/views/applicants/_phone_fields.html.erb
<div class='nested-fields'>
  <div class='phoneFields'>
    <div class='field'>
      <%= f.label :number, class: 'phone-number-label' %>
      <%= f.text_field :number %>
    </div>
  </div>
  <%= link_to_remove_association t('phones.remove'), f %>
</div>

app/views/applicants/index.html.erb
<nav>
  <h1><%= t('models.applicant.index', scope: :activerecord) %></h1>
</nav>
<div class='triangle'></div>

<div class='content-container'>
  <div class='content'>
  <h2><%= t('models.applicant.index', scope: :activerecord) %></h2>
  <hr />
  <% if @applicants.any? %>
    <% @applicants.each do |applicant| %>
      <%= link_to  applicant.social_name, applicant_path(applicant) %>
    <% end %>
  <% end %>

app/views/applicants/new.html.erb
<nav class='new-applicant-nav'>
  <h1><%= t('models.applicant.create') %></h1>
</nav>
<div class='applicant-new-triangle'></div>
<% if @applicant.errors.any? %>
  <div class='errors'>
    <% @applicant.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>
<div class='form-applicant-container'>
  <%= render partial: 'form', locals: { applicant: @applicant } %>
</div>

app/views/applicants/show.html.erb
<nav>
  <h1><%= t('models.applicant.show', scope: :activerecord) %></h1>
</nav>
<div class='applicant-show-triangle'></div>
<div class='content'>
  <table style='width:100%'>
    <tr>
      <th>
        <%= t('attributes.applicant.social_name', scope: :activerecord) %>:
      </th>
      <td>
        <%= @applicant.social_name %>
      </td>
    </tr>
    <tr>
      <th>
        <%= t('attributes.applicant.cnpj', scope: :activerecord) %>:
      </th>
      <td>
        <%= @applicant.cnpj %>
      </td>
    </tr>
    <% @applicant.phones.each do |phone| %>
      <tr>
        <th>
          <%= t('attributes.applicant/phones.number', scope: :activerecord) %>:
        </th>
        <td>
          <%= phone.number %>
        </td>
      </tr>
    <% end %>
    <% @applicant.addresses.each do |address| %>
      <tr>
        <th>
          <%= t('attributes.applicant/addresses.address', scope: :activerecord) %>:
        </th>
        <td>
          <%= address.street %>
          <%= address.number %>
          <%= address.complement %>
        </td>
      </tr>
    <%end %>
    <% @applicant.credit_solicitations.each do |credit| %>
      <tr>
        <th>
          <%= t('models.credit_solicitation.one', scope: :activerecord) %>
        </th>
        <td>
          <%= credit.plots_amount %>x
          <%= number_to_currency(credit.value) %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class='links'>
    <%= link_to t('models.credit_solicitation.index', scope: :activerecord), applicant_credit_solicitations_path(@applicant) %>
    <%= link_to t('models.credit_solicitation.create', scope: :activerecord), new_applicant_credit_solicitation_path(@applicant) %>
  </div>

app/views/credit_solicitations/index.html.erb
<nav class='credit-nav'>
  <h1><%= t('models.credit_solicitation.index', scope: :activerecord) %></h1>
</nav>
<div class='credit-index-triangle'></div>
<div class='credit-index-container'>
  <table>
    <tr>
      <th>
        <%= t('attributes.applicant.social_name', scope: :activerecord) %>
      </th>
      <td>
        <%= @credit_solicitation.applicant.social_name %>
      </td>
    </tr>
    <tr>
      <th>
        <%= t('attributes.credit_solicitation.value', scope: :activerecord) %>
      </th>
      <td>
        <%= number_to_currency(@credit_solicitation.value) %>
      </td>
    </tr>
    <tr>
      <th>
        <%= t('attributes.credit_solicitation.value_with_rate', scope: :activerecord) %>
      </th>
      <td>
        <%= number_to_currency(@credit_solicitation.value_with_rate) %>
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <th><%= t('models.plot.one', scope: :activerecord) %></th>
      <th><%= t('attributes.plot.payment_day', scope: :activerecord) %></th>
      <th><%= t('attributes.plot.value', scope: :activerecord) %></th>
    </tr>
    <% @credit_solicitation.plots.each_with_index do |p, i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= l(p.payment_day)%></td>
        <td><%= number_to_currency(p.value) %></td>
      </tr>
    <% end %>
  </table>

app/views/credit_solicitations/new.html.erb
<nav>
  <h1><%= t('models.credit_solicitation.create', scope: :activerecord) %></h1>
</nav>
<div class='credit-new-triangle'></div>
<% if @credit_solicitation.errors.any? %>
  <div class='errors'>
    <% @credit_solicitation.errors.full_messages.each do |message| %>
      <p>
        <%= message %>
      </p>
    <% end %>
  </div>
<% end %>
<div class='title'>
  <h1>Solicite Seu Emprestimo</h1>
</div>
<div class='form-container'>
  <%= form_with model: [:applicant, @credit_solicitation], local: true do |f| %>
    <%= f.hidden_field :applicant_id, value: @credit_solicitation.applicant_id %>
    <div class='field'>
      <%= f.label :value %>
      <%= f.text_field :value %>
    </div>
    <div class='field'>
      <%= f.label :plot_tax_id %>
      <%= f.collection_select :plot_tax_id, @plot_taxes, :id, :plot, prompt: true %>
    </div>
    <div class='field'>
      <%= f.submit 'Registrar', class: 'submit-button' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<nav>
  <h2>Emprestimo</h2>
  <h2>Como Funciona</h2>
  <% if user_signed_in? %>
    <%= link_to t('models.applicant.index', scope: :activerecord), applicants_path %>
    <%= link_to t('shared.links.sign_out', scope: :devise), destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to t('shared.links.sign_in', scope: :devise), new_user_session_path %>
  <% end %>
</nav>
<div class='triangle'>
  <div class='triangle_content'>
  <%= image_tag  "Logo.png" %>
  <h2>Nexoos Challenge</h2>
  </div>
</div>
<div class='home-content'>
  <h2>Empréstimo na Nexoos é simples <br/>e sem complicação</h2>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NexoosChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "#{controller.controller_name}-#{controller.action_name}" %>">
    <% if !notice.nil? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if !alert.nil? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <main>
      <div class='side-bar'>
        <div class='circle'></div>
          <%= link_to t('models.applicant.create', scope: :activerecord), new_applicant_path, class: 'new-applicant' %>
          <%= link_to t('models.applicant.index', scope: :activerecord), applicants_path, class: 'applicant-index' %>
          <%= link_to t('shared.links.sign_out', scope: :devise), destroy_user_session_path, method: :delete, class: 'destroy-session' %>
          <%= image_tag  "Logo_white.png" %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>